[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[volumes]]
name = "telegram-data"
path = "/data"
persistent = true
mount_path = "/data"
size = "1Gi" 